class_name Opcodes

enum {
	#MATCH LIFECYCLE AND PREPERATION
	SERVER_MATCH_PHASE_CHANGED = 100,
	SERVER_MATCH_CANCELLED = 101,
	CLIENT_PLAYER_SETUP = 105,

	SERVER_MATCH_SETUP = 110,
	CLIENT_SETUP_RECEIVED = 111,
	CLIENT_SETUP_FAILED = 112,

	CLIENT_LOADING_PROGRESS = 120,
	CLIENT_ASSETS_READY = 121,
	CLIENT_ASSETS_FAILED = 122,

	SERVER_START_SCHEDULED = 130,
	SERVER_MATCH_STARTED = 131,
	
	#CLOCK AND SYNCHRONIZATION
	CLIENT_PING = 200,
	SERVER_PONG = 201,
	SERVER_CLOCK_SYNC = 210,
	CLIENT_CLOCK_REPORT = 211,
	
	#PLAYER GAMEPLAY COMMANDS
	CLIENT_ATTEMPT_MOVE = 300,
	CLIENT_ATTEMPT_USE_ABILITY = 320,
	CLIENT_SURRENDER = 330,
	
	#AUTHORITATIVE SIMULATION EVENTS
	SERVER_EVENT_BATCH = 400,
	SERVER_COMMAND_REJECTED = 410,
	
	#STATE SNAPSHOTS AND RECOVERY
	SERVER_STATE_SNAPSHOT = 500,
	SERVER_STATE_CORRECTION = 510,
	SERVER_RECONNECTION_STATE = 520,
	CLIENT_RECONNECTION_READY = 521,
	
	#IN-MATCH SOCIAL AND SPECTATORS
	CLIENT_COMBAT_EMOTE = 600,
	SERVER_COMBAT_EMOTE = 601,
	
	#MATCH TERMINATION AND RESULTS
	SERVER_MATCH_ENDING = 700,
	SERVER_MATCH_RESULT = 710,
	
	#ERRORS, DAIGNOSTICS, AND REPORTS
	SERVER_PROTOCOL_ERROR = 800,
	SERVER_RATE_LIMITED = 801,
	SERVER_UNSUPPORTED_MESSAGE = 802,
	CLIENT_DIAGNOSTIC_REPORT = 820,
	
	#EXPERIMENTAL/RESERVED
	SEND_TEXT = 900,
	CONFIRMED_TEXT = 901
}
